### ISSUE TITLE
Cannot use vim-pyenv-(de)activate-post hooks.

### ISSUE THREAD

**Issue by razor-x** [lambdalisue/vim-pyenv#10]
I could not get this example to work:

```vim
if jedi#init_python()
  function! s:jedi_auto_force_py_version() abort
    let major_version = pyenv#python#get_internal_major_version()
    call jedi#forec_py_version(major_version)
  endfunction
  augroup vim-pyenv-custom-augroup
    autocmd! *
    autocmd vim-pyenv-activate-post   * call s:jedi_auto_force_py_version()
    autocmd vim-pyenv-deactivate-post * call s:jedi_auto_force_py_version()
  augroup END
endif
```

Error is `E216: No such group or event: vim-pyenv-activate-post * call s:jedi_auto_force_py_version()`

As far as I can tell, `vim-pyenv-activate-post` and `vim-pyenv-deactivate-post` are not actually defined anywhere in the source. If that's the case, I don't see how this works either: https://github.com/lambdalisue/vim-pyenv/blob/master/autoload/pyenv/info.vim#L73-L78

**Comment by lambdalisue** [comment]
Oops. My bad. `User` was missed in example and extra `*` was specified.
The configure should be like:
```vim
if jedi#init_python()
  function! s:jedi_auto_force_py_version() abort
    let major_version = pyenv#python#get_internal_major_version()
    call jedi#forec_py_version(major_version)
  endfunction
  augroup vim-pyenv-custom-augroup
    autocmd! *
    autocmd User vim-pyenv-activate-post call s:jedi_auto_force_py_version()
    autocmd User vim-pyenv-deactivate-post call s:jedi_auto_force_py_version()
  augroup END
endif
```

Ref: https://github.com/lambdalisue/rook/blob/master/home/.vim/rc/neobundle.config.vim#L2063

**Comment by lambdalisue** [comment]
I updated the documents. Thanks for reporting :-)

**Comment by lambdalisue** [comment]
In case if you are interested in `AutoCmd`. The `vim-pyenv-(de)activate-post` is called as a user defined autocmd in https://github.com/lambdalisue/vim-pyenv/blob/986fae636a51c0ffe29852dc83e31a836df8025b/autoload/pyenv.vim#L22 See `:help autocmd` for more detail about user defined autocmd :-)

**Comment by razor-x** [comment]
I recently tested to see if this was working for me, but it seems it's not actually switching the jedi python version.

Here is a minimal `vimrc` to test it (using [vim-plug](https://github.com/junegunn/vim-plug)).

```vim
set nocompatible
filetype off
call plug#begin($HOME . '/.vim/plugged.test')
Plug 'davidhalter/jedi-vim'
     \ | Plug 'lambdalisue/vim-pyenv'
call plug#end()

if jedi#init_python()
  function! s:jedi_auto_force_py_version() abort
    let major_version = pyenv#python#get_internal_major_version()
    call jedi#force_py_version(major_version)
  endfunction
  augroup python-pyenv-jedi
    autocmd!
    autocmd User vim-pyenv-activate-post   call s:jedi_auto_force_py_version()
    autocmd User vim-pyenv-deactivate-post call s:jedi_auto_force_py_version()
  augroup END
endif
```

Tested as follows (Python 3.5.0 installed first using pyenv and vim-plug installed normally):

1. Save test config to `vimrc`.
2. Open vim with `vim -u vimrc` (ignore warning).
3. Run `:PlugInstall` and close vim.
4. Create `test.py` and open vim with `vim -u vimrc-test test.py`.
5. Run `:PyenvActivate 3.5.0` and see `vim-pyenv: "3.5.0" is activated.`
6. Run `:JediDebugInfo` and see `Using Python version: 2`.

From what I can tell, I don't think the autocmd is being run, and even when I force run it with `:execute 'doautocmd User vim-pyenv-activate-post'` it doesn't switch the version.

**Comment by lambdalisue** [comment]
Then may be `call jedi#force_py_version(major_version)` changed? Can you change the version with the command?

**Comment by razor-x** [comment]
Just tested the example with updated plugins and it appears to be working now. (Maybe fixed in jedi?)
