### ISSUE TITLE
Add ctags for active environment

### ISSUE THREAD

**Issue by razor-x** [lambdalisue/vim-pyenv#11]
There doesn't seem to be anything like [rbenv-ctags](https://github.com/tpope/rbenv-ctags) or [gem-ctags](https://github.com/tpope/gem-ctags) for Ruby, but for environments created with, e.g., 

```bash
$ pyenv virtualenv 3.4.3 my-project
```
I can do

```bash
$ ctags -o $(pyenv prefix)/tags -R $(pyenv prefix)
```

To generate and update all ctags for the Python environment.

It would be cool if this plugin would add `$(pyenv prefix)/tags` to vim's tag list if it exists. Also it should keep the tag list consistent when the environment is activated and deactivated, i.e., remove the tags file from the tag list on deactivate, and add the tags file on activate.

**Comment by lambdalisue** [comment]
Hum... OK. I'll consider about it. I'm a bit busy now thus probably it takes time (the implementation sounds easy though)

**Comment by lambdalisue** [comment]
It took so long but finally the following new commands and variables are implemented.

- `:PyenvCreateCtags` - Create ctags of the current activated pyenv as you showed me
- `:PyenvAssignCtags` - Assign ctags created via `:PyenvCreateCtags` to vim's tag list.
- `:PyenvWithdrawCtags` - Withdraw ctags from vim's tag list
- `g:pyenv#auto_create_ctags` - Automatically create ctags every after activation. quite slow.
- `g:pyenv#auto_assign_ctags` - Automatically assign catgs every after activation.

See `:help vim-pyenv` for more details :-)

**Comment by Govinda-Fichtner** [comment]
@razor-x Is the generation of ctags happening asynchronously?

**Comment by Govinda-Fichtner** [comment]
@razor-x Ping

**Comment by lambdalisue** [comment]
Sorry for delay. Well, unfortunately it's not.

**Comment by Govinda-Fichtner** [comment]
@lambdalisue Is there already a way to do stuff async in vim-pyenv? And vim-pyenv should probably work in Vim and Neovim, right? 

I am just wondering how much effort it would be to make the ctags generation async... There a lot of tag vim plugins out there that already do this in an async and incremental fashion.

For my virtual envs it blocks the editor for easily 30s when I activate virtualenv.
Making this async would be huge benefit.
