### ISSUE TITLE
Error detected while processing function pyenv#activate

### ISSUE THREAD

**Issue by samuell** [lambdalisue/vim-pyenv#14]
I have a .vimrc file with only (everything else commented out):
```vim
execute pathogen#infect()
syntax on
filetype plugin indent on
```
... and only vim-pyenv in `~/.vim/bundle/`.

Still I get the following errors when opening vim:
```bash
"~/.vimrc" 85L, 2853C^[[>1;2802;0c
Error detected while processing function pyenv#activate..<SNR>18_activate..pyenv#python#exec_code..<SNR>42_exec_code:
line    4:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function pyenv#activate..<SNR>18_activate..pyenv#python#exec_code..<SNR>42_exec_code:
line    4:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function pyenv#activate..<SNR>18_activate..pyenv#python#exec_code..<SNR>42_exec_code:
line    4:
AttributeError: 'module' object has no attribute 'vars'
```
**System info:**
- OS: Scientific Linux (RHEL) 6
- VIM: VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Apr  5 2012 05:28:37)
- PyEnv: 0.4.0-20140520-738-g0c81c97
- Python (activated in pyenv): 2.7.6

Any hints are very welcome.

**Comment by samuell** [comment]
I don't see this error on my laptop though, (running Xubuntu 14.04 LTS 64bit).

**Comment by samuell** [comment]
Well, I'm figuring now this might have to do with an over-loaded NFS-mounted storage, that my home-directory resides on, on the actual system :/ ... will continue to investigate ...

**Comment by samuell** [comment]
Well, it turns out the vim python module on that other system is missing the 'vars' attribute, among others. 

If I run:
```vim
:python import vim; print 'vars' in dir(vim)
```
Then on the Scientific Linux system, i get "False", while on Xubuntu, I get "True".

Actually, there is quite a difference in the attributes list:

On Scientific Linux:
```python
:python import vim; print dir(vim)
['__doc__', '__name__', '__package__', 'buffers', 'command', 'current', 'error', 'eval', 'windows']
```

On Xubuntu
```python
:python import vim; print dir(vim)
['Buffer', 'Dictionary', 'Function', 'List', 'Options', 'Range', 'TabPage', 'VAR_DEF_SCOPE', 'VAR_FIXED'
, 'VAR_LOCKED', 'VAR_SCOPE', 'VIM_SPECIAL_PATH', 'Window', '_Loader', '__doc__', '__name__', '__package_
_', '_chdir', '_fchdir', '_find_module', '_get_paths', '_getcwd', '_load_module', 'bindeval', 'buffers',
 'chdir', 'command', 'current', 'error', 'eval', 'fchdir', 'find_module', 'foreach_rtp', 'options', 'os'
, 'path_hook', 'strwidth', 'tabpages', 'vars', 'vvars', 'windows']
```

**Comment by samuell** [comment]
Ok, solved this now by compiling my own vim 7.4 in my home folder.

Just for reference:
```bash
cd vim74
./configure --disable-gui --enable-pythoninterp --prefix=$HOME
make
make install
```

**Comment by lambdalisue** [comment]
Just for mention.

> VIM: VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Apr 5 2012 05:28:37)

All of my vim plugins, including vim-pyenv, does not support Vim earlier than 7.3 (most of does not support 7.3 as well).

**Comment by samuell** [comment]
@lambdalisue : Thanks, good to know!
