### ISSUE TITLE
How to automatically pickup a python version with autocmd

### ISSUE THREAD

**Issue by owais** [lambdalisue/vim-pyenv#15]
It would be really useful if vim-pyenv could read .python-version from the current directory and activate it automatically.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/vim-pyenv/blob/master/doc/vim-pyenv.txt#L180-L184

`pyenv#activate()` will call https://github.com/lambdalisue/vim-pyenv/blob/master/autoload/pyenv.vim#L9-L11 and it get current selected python version(s) by https://github.com/lambdalisue/vim-pyenv/blob/master/autoload/pyenv/pyenv.vim#L49-L61 thus I think this feature is already implemented from the initial version.

What kind of value would be shown when you call `echo pyenv#pyenv#get_selected_envs()`?

**Comment by owais** [comment]
It was not working so I added this to my vimrc. Works now.

```viml
function! LoadCurrentPyenv()
  if filereadable('.python-version')
    let env_name = substitute(system('echo "$(cat .python-version)"'), '\n\+$', '', '')
    call pyenv#activate(env_name)
  endif
endfunction

autocmd FileType python call LoadCurrentPyenv()
```

**Comment by lambdalisue** [comment]
What kind of value would be shown when you call echo pyenv#pyenv#get_selected_envs()?

**Comment by owais** [comment]
Well now it shows the correct one but if I remove the function I created above, it shows `[system]`

**Comment by lambdalisue** [comment]
Then what about `echo getcwd()`? Is is the directory where `.python-version` exist?

**Comment by owais** [comment]
> Then what about echo getcwd()? Is is the directory where .python-version exist?
Yes. It shows the same directory (project root) which contains `.python-version`

**Comment by lambdalisue** [comment]
Then what about 

`echo pyenv#utils#system(join([g:pyenv#pyenv_exec, 'version']))`

Could you paste the result?

**Comment by owais** [comment]
<img width="1224" alt="screen shot 2015-12-27 at 10 35 27 pm" src="https://cloud.githubusercontent.com/assets/46186/12011192/2ffcc6de-acea-11e5-996f-8afee9bf48f4.png">

**Comment by lambdalisue** [comment]
Btw, Did you mean you would like to automatically pickup version of python every time when you open a python file? I'm asking this because I'm talking about the python version when you open a Vim.

**Comment by lambdalisue** [comment]
If you would like to pick up every time. You need

```vim
augroup my_vim_pyenv_load
  autocmd! *
  autocmd FileType python PyenvActivate
augroup END
```

**Comment by lambdalisue** [comment]
If you are talking about when you start the Vim. Your environment has `PYENV_VERSION` variable **prior to vim-pyenv** that why you cannot detect a correct one I guess.

**Comment by owais** [comment]
Nice. That solves it without having to read .python-version manually above. Thanks!
