### ISSUE TITLE
Error detected while processing function pyenv#activate

### ISSUE THREAD

**Issue by oblitum** [lambdalisue/vim-pyenv#22]
In normal conditions when I launch vim or neovim from command line I generally don't get these errors, but since I started using tmuxp to load tmux pane layouts, and loading vim/neovim in some of those panes, I always get this error when vim/neovim is launched by tmuxp:

```
Error detected while processing function pyenv#activate[2]..<SNR>206_activate[11]..pyenv#pyenv#activate[1]..<SNR>207_activate[6]..pyenv#python#get_external_major_version[1]..<SNR>213_get_external_major_version[1]..<SNR>213_get_external_version:
line    9:
E684: list index out of range: 1
Error detected while processing function pyenv#activate[2]..<SNR>206_activate[11]..pyenv#pyenv#activate[1]..<SNR>207_activate[6]..pyenv#python#get_external_major_version[1]..<SNR>213_get_external_major_version[1]..<SNR>213_get_external_version:
line    9:
E15: Invalid expression: split(result.stdout)[1]
```

tmuxp is an utilitary that can be used to simply launch tmux sessions with preconfigured panes and applications. I don't get why when vim is launched via tmuxp I always get this, it seems related with some issue in the loading phase of the plugin, because differently of just starting vim by hand, when I start it via tmuxp, tmuxp launches a bunch of things in sequence, sessions, panes (with their zsh instances, which may relate with temporarily missing stdout?), and vim instances. It seems this bunch of loading stuff that's causing something to plugin loading order that affects vim-pyenv only.

**Comment by oblitum** [comment]
OK, I just confirmed that changing my tmuxp recipe from this:

```yaml
session_name: rust
start_directory: ./
shell_command_before:
  - tmux set status off
  - cls
windows:
- layout: main-vertical
  options:
    main-pane-width: 160
  panes:
  - shell_command:
    - nvim sample.rs
    focus: true
  - blank
```

to this (notice the sleep):

```yaml
session_name: rust
start_directory: ./
shell_command_before:
  - tmux set status off
  - cls
windows:
- layout: main-vertical
  options:
    main-pane-width: 160
  panes:
  - shell_command:
    - sleep 0.2
    - nvim sample.rs
    focus: true
  - blank
```

I can avoid the issue.

I'm not sure whether the plugin can solve this by itself, but if not, feel free to close the issue.

**Comment by oblitum** [comment]
cc @tony, do you think it's wise for tmuxp to have a small implicit `sleep` before commands to avoid these kind of problems?

**Comment by tony** [comment]
What's your pyenv in your dot config look like? There's no virtualenv, right?

**Comment by oblitum** [comment]
@tony no virtualenv loaded in this sample, but the plugin get's loaded anyway from .vimrc.

**Comment by tony** [comment]
It looks like pyenv isn't getting sourced into the pane before vim starts.

Is there any sort of env variable set with pyenv activates successfully? Can you try `echo`'ing it before vim begins to see if it's loading?

Any other sort of plugin you're using?

**Comment by oblitum** [comment]
@tony this happens intermittently, I just updated my machine and reboot for other stuff and now the issue isn't reproducing anymore, but it always comes back... so for the moment I'm unable to reproduce it. From what I've checked pyenv sets `$PYENV_VIRTUALENV_INIT` to `1`.

**Comment by tony** [comment]
We need more information to isolate  the issue, So far it looks like the pyenv isn't getting init'd by the time vim opens.

We can either close the issue for now and reopen when it recurs, or keep it open and see if more info comes in.

**Comment by oblitum** [comment]
@tony I have another issue that may be related and which also could possibly be fixed with delays before commands. I have a recipe for loading 3 mutt instances, each one in its own window/pane (one instance per mail account). Sometimes when I `tmuxp load` this recipe, it fails to load one of the accounts because of a GPG lock that's in use by the other being open at the same time.

**Comment by tony** [comment]
have you considered trying a ``before_script`` script? Those run and double check things before tmuxp begins building the workspace.

**Comment by oblitum** [comment]
@tony no but, in these cases the target program instances, mutt or vim, must come after the workspace if I understand it correctly.

**Comment by oblitum** [comment]
@tony I don't see how `before_script` can fix the concurrency problem when those target programs need to start.

**Comment by tony** [comment]
> Sometimes when I tmuxp load this recipe, it fails to load one of the accounts because of a GPG lock that's in use by the other being open at the same time.

I reread that.

I never experienced that exact issue.  So loading mutt can fail if they're initiated at the same time, because GPG is going its thing?

Is it correct to say, it would be fixed if they started at a separate time (like 1-3 seconds apart?)

**Comment by oblitum** [comment]
The way I'm fixing it by now is:

```yaml
shell_command_before:
  - sleep 0.2
```

Expecting a sleep before the sequence of commands to solve the concurrency issues.

**Comment by oblitum** [comment]
> I reread that.

> I never experienced that exact issue. So loading mutt can fail if they're initiated at the same time, because GPG is going its thing?

> Is it correct to say, it would be fixed if they started at a separate time (like 1-3 seconds apart?)

Yes. GPG locks my key for opening one account, I think for a rather brief instant, hence this issue happens once in a while only when opening the three accounts recipe.

**Comment by tony** [comment]
Sleeping is one work around.

The other, maybe there is a way to programmatically poll for the lock to not exist (if it does, retry). 

Perhaps a shell script to wrap mutt.

Either by checking for the lock file, or accessing gpg in a way that doesn't succeed unless/until the lock is freed [1]

[1] Saw this: `/usr/bin/gpg --no-verbose --batch --with-colons --list-keys` @ https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=58260

**Comment by oblitum** [comment]
Got it, but I guess I'm gonna stick with the sleeps as this stuff is only happening in this tmuxp scenery and it solves both problems.

**Comment by tony** [comment]
sleep seems like a cool work around, it's the first i've seen that in a tmuxp config

**Comment by oblitum** [comment]
I'm gonna close this as I think it's not worth the effort to find a fix in the plugin.

**Comment by tony** [comment]
got it. if this comes up again feel free to reopen 👍

**Comment by oblitum** [comment]
@tony your creation now lives beyond the creator :-)
