### ISSUE TITLE
pyenv not activating with :py3

### ISSUE THREAD

**Issue by justin8** [lambdalisue/vim-pyenv#27]
Hey,

I'm trying to use vim-pyenv in an environment with completor (instead of using jedi directly), with +python3 -python on OSX. I can find packages installed only in the pyenv environment in the autocompletion menu successfully, which is good, but when I run `:py3 import sys; print(sys.version)` it reports the system python is being used, and not the activated pyenv one.

Is this expected?

**Comment by lambdalisue** [comment]
Could you give me step by step procedure? I don't really get your situation.

**Comment by justin8** [comment]
Sure, my vimrc is here: https://github.com/justin8/dotfiles/blob/master/install-files/files/.vimrc

I have a single pyenv environment for v3.6.1, my system python3 is 3.6.3.
I open a python file, and type `import bo` and can't match boto3
On the pyenv environment, I install boto3: `pip3 install boto3`, enabling `system` version in pyenv shows it is only on the pyenv 3.6.1 install.
Opening a python file in vim, I type `import bo` and it autocompletes to `boto3`, confirming it is working in the pyenv environment.

However, when I run `:py3 import sys; print(sys.version)` it prints 3.6.3; the system version, and not the pyenv one. Even though the autocompletion is using the pyenv version.

**Comment by lambdalisue** [comment]
What is the output of

1. `python --version` on your terminal
2. `:!python --version` on your Vim

are they equal?

**Comment by justin8** [comment]
They both report 3.6.1, which is the correct one from pyenv

**Comment by lambdalisue** [comment]
Oops. I misread.

> However, when I run :py3 import sys; print(sys.version) it prints 3.6.3; the system version, and not the pyenv one. Even though the autocompletion is using the pyenv version.

It is correct behavior. While `:py` or `:py3` is statically linked to the python which was available when Vim has built, it (usually) returns the system version.

This library is to fix `sys.path` to make completion enable so autocompletion is using the pyenv version. You can check it by

```
:py3 import sys; print(sys.path)
```

Before and after you've activate via `PyenvActivate`

**Comment by justin8** [comment]
Ah ok, thanks for investigating
